server:
  port: 8070
spring:
  application:
    name: microadministrador
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/administrador?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
