spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: microcuenta
            uri: http://localhost:8060/**
            predicates:
              - Path=/cuenta/**
          - id: microestacion
            uri: http://localhost:8050/**
            predicates:
              - Path=/estacion/**
          - id: microfacturacion
            uri: http://localhost:8040/**
            predicates:
              - Path=/facturacion/**
          - id: micromantenimiento
            uri: http://localhost:8030/**
            predicates:
              - Path=/mantenimiento/**
          - id: micromonopatin
            uri: http://localhost:8020/**
            predicates:
              - Path=/monopatin/**
          - id: microusuario
            uri: http://localhost:8010/**
            predicates:
              - Path=/usuario/**
          - id: microviaje
            uri: http://localhost:8000/**
            predicates:
              - Path=/viaje/**
          - id: microadministrador
            uri: http://localhost:8070/**
            predicates:
              - Path=/administrador/**
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql


server:
  port: 8090

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

