services:
  microAdministrador:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: administrador
    ports:
      - "3306:3306"
    networks:
      - mysql_network

  microfacturacion:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: facturacion
    ports:
      - "3307:3306"
    networks:
      - mysql_network

  microMonopatin:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: monopatin
    ports:
      - "3308:3306"
    networks:
      - mysql_network

  microViaje:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: viaje
    ports:
      - "3309:3306"
    networks:
      - mysql_network

  mysql_auth:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: auth
    ports:
      - "3310:3306"
    networks:
      - mysql_network


  microusuario:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: usuario
    ports:
      - "3311:3306"
    networks:
      - mysql_network

  microCuenta:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: cuenta
    ports:
      - "3312:3306"
    networks:
      - mysql_network


  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
       MONGO_INITDB_DATABASE: estacion
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
