server:
    port: 8050

spring:
    application:
        name: microestacion
    data:
        mongodb:
            uri: mongodb+srv://user1:arquitecturas@cluster0.olyxl.mongodb.net/estacion?retryWrites=true&w=majority&appName=Cluster0

    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


